// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PilotLog$Type } from "./PilotLog";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PilotLog"]: PilotLog$Type;
    ["contracts/PilotLog.sol:PilotLog"]: PilotLog$Type;
  }

  interface ContractTypesMap {
    ["PilotLog"]: GetContractReturnType<PilotLog$Type["abi"]>;
    ["contracts/PilotLog.sol:PilotLog"]: GetContractReturnType<PilotLog$Type["abi"]>;
  }
}
