// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Licenses$Type } from "./Licenses";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Licenses"]: Licenses$Type;
    ["contracts/Licenses.sol:Licenses"]: Licenses$Type;
  }

  interface ContractTypesMap {
    ["Licenses"]: GetContractReturnType<Licenses$Type["abi"]>;
    ["contracts/Licenses.sol:Licenses"]: GetContractReturnType<Licenses$Type["abi"]>;
  }
}
