// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Licenses$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Licenses",
  "sourceName": "contracts/Licenses.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "name": "licenses",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600f57600080fd5b5060c080601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063f18a02c614602d575b600080fd5b604a6038366004605c565b60006020819052908152604090205481565b60405190815260200160405180910390f35b600060208284031215606d57600080fd5b81356001600160a01b0381168114608357600080fd5b939250505056fea26469706673582212203525f7045bb8a9ba44c1911d245a5d61e28d9e01ede34a64c430ccfad103eba264736f6c634300081a0033",
  "deployedBytecode": "0x6080604052348015600f57600080fd5b506004361060285760003560e01c8063f18a02c614602d575b600080fd5b604a6038366004605c565b60006020819052908152604090205481565b60405190815260200160405180910390f35b600060208284031215606d57600080fd5b81356001600160a01b0381168114608357600080fd5b939250505056fea26469706673582212203525f7045bb8a9ba44c1911d245a5d61e28d9e01ede34a64c430ccfad103eba264736f6c634300081a0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Licenses",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Licenses$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Licenses.sol:Licenses",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Licenses$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Licenses",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Licenses$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Licenses.sol:Licenses",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Licenses$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Licenses",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Licenses$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Licenses.sol:Licenses",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Licenses$Type["abi"]>>;
}
